### ISSUE TITLE
Make standalone.

### ISSUE THREAD

**Issue by trusktr** [coolwanglu/vim.js#18]
Like how [Atom](http://atom.io) is a standalone web-based editor, make this one standalone. :D

**Comment by jordwalke** [comment]
:+1:

**Comment by coolwanglu** [comment]
Just came across this project: https://github.com/carlosdcastillo/vim-mode which allows atom to talk to neovim.

Cannot convince myself which one (native vim or vim.js) is better for this task, but I prefer a native one.

**Comment by coolwanglu** [comment]
Done. See the `node-webikit/` folder.
A few things not working well:

- `:q` cannot quit vim, which has been fixed in the source code
- Sometimes file cannot be saved, but seems that saving to new files works.
- Filesystem must be mount manually, we cannot mount the root directly (kripken/emscripten#2040), edit `vim.html` to mount directories manually

For the first item, seems that something's wrong with emscripten's js minimizer, I will upload a new version once it's fixed.
